"""Added orgname column

Revision ID: b12c9fd08c00
Revises: 
Create Date: 2024-10-08 15:33:58.923750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12c9fd08c00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orgname', sa.String(length=150), nullable=True))
        batch_op.alter_column('sent_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('sent_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('orgname')

    # ### end Alembic commands ###
